<!--
  ComponentBuilder.vue [ORGANISM]

  Atomic Level: Organism
  Atomic Rationale: Orchestrates AiPromptPanel, AiCodeEditor, AiPreviewPane,
  AiSavePanel, and AiGalleryPanel into the full builder experience. Owns the
  useAiStudio composable instance and passes reactive state down to molecules
  as props. This is the organism for BOTH the Component Builder and the
  Template Builder — the `type` prop controls which variant is active.

  Also used as the Template Builder. The two builders share 100% of their
  structure; the `type` prop drives:
  - The mock data injected into AiPreviewPane (templates only)
  - The "Set as active" toggle in AiSavePanel (templates only)
  - The gallery filter (component gallery vs template gallery)

  Layout (8pt grid, max-w-5xl context from admin shell):

  ┌─────────────────────────────────────────────────────────────┐
  │  AiPromptPanel                                              │ ← full width
  │  textarea + Generate button + AiGenerationStatus           │
  └─────────────────────────────────────────────────────────────┘
  ┌──────────────────────────┐ ┌──────────────────────────────┐
  │  AiCodeEditor            │ │  AiPreviewPane               │
  │  dark textarea           │ │  sandboxed iframe            │
  │  min-h: 320px            │ │  min-h: 320px                │
  └──────────────────────────┘ └──────────────────────────────┘
  ┌─────────────────────────────────────────────────────────────┐
  │  AiSavePanel                                                │
  │  name input + Save button [+ Set as active toggle]         │
  └─────────────────────────────────────────────────────────────┘
  ┌─────────────────────────────────────────────────────────────┐
  │  AiGalleryPanel (collapsible)                               │
  │  [AiGalleryCard] [AiGalleryCard] …                         │
  └─────────────────────────────────────────────────────────────┘

  The code/preview split uses a 1:1 grid (grid-cols-2) on md+ screens.
  On small screens it stacks vertically (single column).

  Note: useAiStudio composable is a stub at design stage — implementation
  will wire up the real Axios calls and Lambda endpoints.
-->
<script setup lang="ts">
import { ref, computed } from 'vue'
import AiPromptPanel from './AiPromptPanel.vue'
import AiCodeEditor from './AiCodeEditor.vue'
import AiPreviewPane from './AiPreviewPane.vue'
import AiSavePanel from './AiSavePanel.vue'
import AiGalleryPanel from './AiGalleryPanel.vue'
import type {
  AiStudioItemType,
  AiGeneratedItem,
  MockArticleData,
} from '@/../product/sections/ai-studio/types'

// ── Props ─────────────────────────────────────────────────────────────────────

const props = defineProps<{
  type: AiStudioItemType
  // Design-stage: gallery and status are passed in from the view layer.
  // In implementation, useAiStudio() composable provides these internally.
  initialGallery?: AiGeneratedItem[]
  initialMockArticle?: MockArticleData
  initialActiveTemplate?: string
}>()

// ── Local state (design prototype — replaced by useAiStudio in implementation) ─

const prompt = ref('')
const generatedCode = ref('')
const generationStatus = ref<'idle' | 'loading' | 'success' | 'error'>('idle')
const generationMessage = ref<string | undefined>(undefined)
const saving = ref(false)
const savedName = ref<string | undefined>(undefined)
const conflictError = ref(false)
const gallery = ref<AiGeneratedItem[]>(props.initialGallery ?? [])
const galleryLoading = ref(false)
const activeTemplateName = ref<string | null>(props.initialActiveTemplate ?? null)

const hasGenerated = computed(() => generatedCode.value.length > 0)

// Mock data is only passed to AiPreviewPane for template type
const mockData = computed<MockArticleData | undefined>(() =>
  props.type === 'template' ? props.initialMockArticle : undefined,
)

// ── Design-stage stubs (real implementation uses useAiStudio composable) ─────

async function handleGenerate() {
  if (!prompt.value.trim()) return
  generationStatus.value = 'loading'
  generationMessage.value = 'Generating with Claude...'

  // Design-time: simulate a response after 1.5s
  await new Promise((r) => setTimeout(r, 1500))

  generatedCode.value = `<script setup lang="ts">
// Generated by AI Studio
const props = defineProps<{
  title: string
  price: number
}>()
<\/script>

<template>
  <div class="rounded-xl border border-slate-200 bg-white p-6">
    <h3 class="text-lg font-semibold text-slate-800">{{ props.title }}</h3>
    <p class="mt-2 text-3xl font-bold text-indigo-600">€{{ props.price }}</p>
    <button class="mt-4 w-full bg-indigo-600 text-white py-2 rounded-lg text-sm font-medium">
      Get started
    </button>
  </div>
</template>`

  generationStatus.value = 'success'
  generationMessage.value = 'Component generated'
}

async function handleSave(name: string) {
  saving.value = true
  conflictError.value = false

  await new Promise((r) => setTimeout(r, 800))

  savedName.value = name
  saving.value = false
  generationStatus.value = 'success'
  generationMessage.value = `Saved as ${name}.vue`
}

function handleSetActive() {
  if (savedName.value) {
    activeTemplateName.value = savedName.value
  }
}

function handleLoadGalleryItem(item: AiGeneratedItem) {
  prompt.value = item.instruction
  generatedCode.value = item.code
  generationStatus.value = 'success'
  generationMessage.value = `Loaded from gallery`
}

function handleDeleteGalleryItem(id: string) {
  gallery.value = gallery.value.filter((i) => i.id !== id)
}
</script>

<template>
  <div class="space-y-4">
    <!-- 1. Prompt panel (full width) -->
    <AiPromptPanel
      v-model="prompt"
      :loading="generationStatus === 'loading'"
      :status="generationStatus"
      :status-message="generationMessage"
      :has-generated="hasGenerated"
      @generate="handleGenerate"
    />

    <!-- 2. Code editor + Preview split -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4" style="min-height: 360px">
      <AiCodeEditor
        v-model="generatedCode"
        language="vue"
      />
      <AiPreviewPane
        :code="generatedCode"
        :mock-data="mockData"
      />
    </div>

    <!-- 3. Save panel -->
    <AiSavePanel
      :type="props.type"
      :saving="saving"
      :saved-name="savedName"
      :is-active="activeTemplateName === savedName"
      :conflict-error="conflictError"
      @save="handleSave"
      @set-active="handleSetActive"
    />

    <!-- 4. Gallery panel (collapsible) -->
    <AiGalleryPanel
      :items="gallery"
      :loading="galleryLoading"
      :active-template-name="activeTemplateName ?? undefined"
      @load="handleLoadGalleryItem"
      @delete="handleDeleteGalleryItem"
    />
  </div>
</template>
